import { supabase } from "./supabase";
import { Quote, CompanySettings } from "./types";

// Helper to convert DB snake_case to App camelCase
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const mapToQuote = (data: any): Quote => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const d = data as Record<string, any>;
    return {
        id: d.id,
        quoteNumber: d.quote_number,
        status: d.status,
        createdAt: d.created_at,
        updatedAt: d.updated_at,
        customerName: d.customer_name,
        honorific: d.honorific,
        issueDate: d.issue_date,
        expiryDate: d.expiry_date,
        taxRate: d.tax_rate,
        subtotal: d.subtotal,
        taxAmount: d.tax_amount,
        totalAmount: d.total_amount,
        items: d.items || [],
        remarks: d.remarks,
    };
};

// Helper to convert App camelCase to DB snake_case
const mapToDb = (quote: Quote) => ({
    // id is auto-generated by DB on insert if undefined, but we need it for updates.
    // simpler to let DB handle ID generation for inserts, or use the one provided.
    id: quote.id || undefined,
    quote_number: quote.quoteNumber,
    status: quote.status,
    customer_name: quote.customerName,
    honorific: quote.honorific,
    issue_date: quote.issueDate,
    expiry_date: quote.expiryDate,
    tax_rate: quote.taxRate,
    subtotal: quote.subtotal,
    tax_amount: quote.taxAmount,
    total_amount: quote.totalAmount,
    items: quote.items,
    remarks: quote.remarks,
    updated_at: new Date().toISOString(),
});

export const getQuotes = async (): Promise<Quote[]> => {
    const { data, error } = await supabase
        .from("quotes")
        .select("*")
        .order("updated_at", { ascending: false });

    if (error) {
        console.error("Error fetching quotes:", error);
        throw error;
    }

    return (data || []).map(mapToQuote);
};

export const getQuote = async (id: string): Promise<Quote | undefined> => {
    const { data, error } = await supabase
        .from("quotes")
        .select("*")
        .eq("id", id)
        .single();

    if (error) {
        console.error("Error fetching quote:", error);
        return undefined;
    }

    return data ? mapToQuote(data) : undefined;
};

export const saveQuote = async (quote: Quote): Promise<void> => {
    // If quote.id is not a valid UUID, Supabase will error.
    // We should strip ID if it's not a UUID to let Supabase generate one.
    const isUuid = (str: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(str);

    const dbData = mapToDb(quote);

    if (!quote.id || !isUuid(quote.id)) {
        delete (dbData as { id?: string }).id;
    }

    const { error } = await supabase
        .from("quotes")
        .upsert(dbData)
        .select();

    if (error) {
        console.error("Error saving quote:", error);
        throw error;
    }
};

export const deleteQuote = async (id: string): Promise<void> => {
    const { error } = await supabase.from("quotes").delete().eq("id", id);

    if (error) {
        console.error("Error deleting quote:", error);
        throw error;
    }
};

// Settings (Using LocalStorage for now as there's no DB table for it yet)
const SETTINGS_KEY = "quotation_app_settings";

export const getSettings = (): CompanySettings => {
    if (typeof window === "undefined") return {
        companyName: "株式会社サンプル",
        address: "東京都渋谷区渋谷1-2-3 サンプルビル 5F",
        zipCode: "150-0002",
        tel: "03-1234-5678",
        email: "info@sample.co.jp",
        registrationNumber: "T1234567890123",
    };
    const data = localStorage.getItem(SETTINGS_KEY);
    return data ? JSON.parse(data) : {
        companyName: "株式会社サンプル",
        address: "東京都渋谷区渋谷1-2-3 サンプルビル 5F",
        zipCode: "150-0002",
        tel: "03-1234-5678",
        email: "info@sample.co.jp",
        registrationNumber: "T1234567890123",
    };
};

export const saveSettings = (settings: CompanySettings): void => {
    localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
};

export const generateQuoteNumber = (): string => {
    const prefix = "QUO";
    const year = new Date().getFullYear();
    const random = Math.floor(Math.random() * 100000).toString().padStart(6, '0');
    return `${prefix}-${year}-${random}`;
}

export const generateId = (): string => {
    return "";
};
